"use strict";

var MoraRomanBuilder = require("../../src/mora/MoraRomanBuilder");
var builder = new MoraRomanBuilder();

describe("Roman Builder Test", () => {
    test("hiragana to roman", () => {
        expect(builder.build("あ")).toEqual(["a"]);
        expect(builder.build("い")).toEqual(["yi", "i"]);
        expect(builder.build("う")).toEqual(["wu", "whu", "u"]);
        expect(builder.build("え")).toEqual(["e"]);
        expect(builder.build("お")).toEqual(["o"]);
        expect(builder.build("か")).toEqual(["ka", "ca"]);
        expect(builder.build("き")).toEqual(["ki"]);
        expect(builder.build("く")).toEqual(["ku", "cu", "qu"]);
        expect(builder.build("け")).toEqual(["ke"]);
        expect(builder.build("こ")).toEqual(["ko", "co"]);
        expect(builder.build("さ")).toEqual(["sa"]);
        expect(builder.build("し")).toEqual(["si", "shi", "ci"]);
        expect(builder.build("す")).toEqual(["su"]);
        expect(builder.build("せ")).toEqual(["se", "ce"]);
        expect(builder.build("そ")).toEqual(["so"]);
        expect(builder.build("た")).toEqual(["ta"]);
        expect(builder.build("ち")).toEqual(["ti", "chi"]);
        expect(builder.build("つ")).toEqual(["tu", "tsu"]);
        expect(builder.build("て")).toEqual(["te"]);
        expect(builder.build("と")).toEqual(["to"]);
        expect(builder.build("な")).toEqual(["na"]);
        expect(builder.build("に")).toEqual(["ni"]);
        expect(builder.build("ぬ")).toEqual(["nu"]);
        expect(builder.build("ね")).toEqual(["ne"]);
        expect(builder.build("の")).toEqual(["no"]);
        expect(builder.build("は")).toEqual(["ha"]);
        expect(builder.build("ひ")).toEqual(["hi"]);
        expect(builder.build("ふ")).toEqual(["hu", "fu"]);
        expect(builder.build("へ")).toEqual(["he"]);
        expect(builder.build("ほ")).toEqual(["ho"]);
        expect(builder.build("ま")).toEqual(["ma"]);
        expect(builder.build("み")).toEqual(["mi"]);
        expect(builder.build("む")).toEqual(["mu"]);
        expect(builder.build("め")).toEqual(["me"]);
        expect(builder.build("も")).toEqual(["mo"]);
        expect(builder.build("や")).toEqual(["ya"]);
        expect(builder.build("ゆ")).toEqual(["yu"]);
        expect(builder.build("よ")).toEqual(["yo"]);
        expect(builder.build("ら")).toEqual(["ra"]);
        expect(builder.build("り")).toEqual(["ri"]);
        expect(builder.build("る")).toEqual(["ru"]);
        expect(builder.build("れ")).toEqual(["re"]);
        expect(builder.build("ろ")).toEqual(["ro"]);
        expect(builder.build("わ")).toEqual(["wa"]);
        expect(builder.build("を")).toEqual(["wo"]);
        expect(builder.build("ん")).toEqual(["nn", "xn"]);
        expect(builder.build("が")).toEqual(["ga"]);
        expect(builder.build("ぎ")).toEqual(["gi"]);
        expect(builder.build("ぐ")).toEqual(["gu"]);
        expect(builder.build("げ")).toEqual(["ge"]);
        expect(builder.build("ご")).toEqual(["go"]);
        expect(builder.build("ざ")).toEqual(["za"]);
        expect(builder.build("じ")).toEqual(["zi", "ji"]);
        expect(builder.build("ず")).toEqual(["zu"]);
        expect(builder.build("ぜ")).toEqual(["ze"]);
        expect(builder.build("ぞ")).toEqual(["zo"]);
        expect(builder.build("だ")).toEqual(["da"]);
        expect(builder.build("ぢ")).toEqual(["di"]);
        expect(builder.build("づ")).toEqual(["du"]);
        expect(builder.build("で")).toEqual(["de"]);
        expect(builder.build("ど")).toEqual(["do"]);
        expect(builder.build("ば")).toEqual(["ba"]);
        expect(builder.build("び")).toEqual(["bi"]);
        expect(builder.build("ぶ")).toEqual(["bu"]);
        expect(builder.build("べ")).toEqual(["be"]);
        expect(builder.build("ぼ")).toEqual(["bo"]);
        expect(builder.build("ぱ")).toEqual(["pa"]);
        expect(builder.build("ぴ")).toEqual(["pi"]);
        expect(builder.build("ぷ")).toEqual(["pu"]);
        expect(builder.build("ぺ")).toEqual(["pe"]);
        expect(builder.build("ぽ")).toEqual(["po"]);
        expect(builder.build("いぇ")).toEqual(["ye", "yixe", "yile", "ixe", "ile"]);
        expect(builder.build("うぃ")).toEqual(["wi", "wuxi", "wuli", "whuxi", "whuli", "uxi", "uli"]);
        expect(builder.build("うぇ")).toEqual(["we", "wuxe", "wule", "whuxe", "whule","uxe", "ule"]);
        expect(builder.build("きゃ")).toEqual(["kya", "kixya", "kilya"]);
        expect(builder.build("きぃ")).toEqual(["kyi", "kixi", "kili"]);
        expect(builder.build("きゅ")).toEqual(["kyu", "kixyu", "kilyu"]);
        expect(builder.build("きぇ")).toEqual(["kye", "kixe", "kile"]);
        expect(builder.build("きょ")).toEqual(["kyo", "kixyo", "kilyo"]);
        expect(builder.build("ぎゃ")).toEqual(["gya", "gixya", "gilya"]);
        expect(builder.build("ぎぃ")).toEqual(["gyi", "gixi", "gili"]);
        expect(builder.build("ぎゅ")).toEqual(["gyu", "gixyu", "gilyu"]);
        expect(builder.build("ぎぇ")).toEqual(["gye", "gixe", "gile"]);
        expect(builder.build("ぎょ")).toEqual(["gyo", "gixyo", "gilyo"]);
        expect(builder.build("くぁ")).toEqual(["qa", "kwa", "kuxa", "kula", "cuxa", "cula", "quxa", "qula"]);
        expect(builder.build("くぃ")).toEqual(["qi", "kwi", "kuxi", "kuli", "cuxi", "culi", "quxi", "quli"]);
        expect(builder.build("くぇ")).toEqual(["qe", "kwe", "kuxe", "kule", "cuxe", "cule", "quxe", "qule"]);
        expect(builder.build("くぉ")).toEqual(["qo", "kwo", "kuxo", "kulo", "cuxo", "culo", "quxo", "qulo"]);
        expect(builder.build("しゃ")).toEqual(["sha", "sya", "sixya", "silya", "shixya", "shilya", "cixya", "cilya"]);
        expect(builder.build("しぃ")).toEqual(["syi", "sixi", "sili", "shixi", "shili",  "cixi", "cili"]);
        expect(builder.build("しゅ")).toEqual(["shu", "syu", "sixyu", "silyu", "shixyu", "shilyu", "cixyu", "cilyu"]);
        expect(builder.build("しぇ")).toEqual(["she", "sye", "sixe", "sile", "shixe", "shile", "cixe", "cile"]);
        expect(builder.build("しょ")).toEqual(["sho", "syo", "sixyo", "silyo", "shixyo", "shilyo", "cixyo", "cilyo"]);
        expect(builder.build("じゃ")).toEqual(["ja", "jya", "zixya", "zilya", "jixya", "jilya"]);
        expect(builder.build("じぃ")).toEqual(["jyi", "zixi", "zili", "jixi", "jili"]);
        expect(builder.build("じゅ")).toEqual(["ju", "jyu", "zixyu", "zilyu", "jixyu", "jilyu"]);
        expect(builder.build("じぇ")).toEqual(["je", "jye", "zixe", "zile", "jixe", "jile"]);
        expect(builder.build("じょ")).toEqual(["jo", "jyo", "zixyo", "zilyo", "jixyo", "jilyo"]);
        expect(builder.build("ちゃ")).toEqual(["cha", "cya", "tya", "tixya", "tilya", "chixya", "chilya"]);
        expect(builder.build("ちぃ")).toEqual(["cyi", "tyi", "tixi", "tili", "chixi", "chili"]);
        expect(builder.build("ちゅ")).toEqual(["chu", "cyu", "tyu", "tixyu", "tilyu", "chixyu", "chilyu"]);
        expect(builder.build("ちぇ")).toEqual(["che", "cye", "tye", "tixe", "tile", "chixe", "chile"]);
        expect(builder.build("ちょ")).toEqual(["cho", "cyo", "tyo", "tixyo", "tilyo", "chixyo", "chilyo"]);
        expect(builder.build("ぢぃ")).toEqual(["dyi", "dixi", "dili"]);
        expect(builder.build("ぢゅ")).toEqual(["dyu", "dixyu", "dilyu"]);
        expect(builder.build("ぢぇ")).toEqual(["dye", "dixe", "dile"]);
        expect(builder.build("ぢょ")).toEqual(["dyo", "dixyo", "dilyo"]);
        expect(builder.build("つぁ")).toEqual(["tsa", "tuxa", "tula", "tsuxa", "tsula"]);
        expect(builder.build("つぃ")).toEqual(["tsi", "tuxi", "tuli", "tsuxi", "tsuli"]);
        expect(builder.build("つぇ")).toEqual(["tse", "tuxe", "tule", "tsuxe", "tsule"]);
        expect(builder.build("つぉ")).toEqual(["tso", "tuxo", "tulo", "tsuxo", "tsulo"]);
        expect(builder.build("てゃ")).toEqual(["tha", "texya", "telya"]);
        expect(builder.build("てぃ")).toEqual(["thi", "texi", "teli"]);
        expect(builder.build("てゅ")).toEqual(["thu", "texyu", "telyu"]);
        expect(builder.build("てぇ")).toEqual(["the", "texe", "tele"]);
        expect(builder.build("てょ")).toEqual(["tho", "texyo", "telyo"]);
        expect(builder.build("でゃ")).toEqual(["dha", "dexya", "delya"]);
        expect(builder.build("でぃ")).toEqual(["dhi", "dexi", "deli"]);
        expect(builder.build("でゅ")).toEqual(["dhu", "dexyu", "delyu"]);
        expect(builder.build("でぇ")).toEqual(["dhe", "dexe", "dele"]);
        expect(builder.build("でょ")).toEqual(["dho", "dexyo", "delyo"]);
        expect(builder.build("にゃ")).toEqual(["nya", "nixya", "nilya"]);
        expect(builder.build("にぃ")).toEqual(["nyi", "nixi", "nili"]);
        expect(builder.build("にゅ")).toEqual(["nyu", "nixyu", "nilyu"]);
        expect(builder.build("にぇ")).toEqual(["nye", "nixe", "nile"]);
        expect(builder.build("にょ")).toEqual(["nyo", "nixyo", "nilyo"]);
        expect(builder.build("ひゃ")).toEqual(["hya", "hixya", "hilya"]);
        expect(builder.build("ひぃ")).toEqual(["hyi", "hixi", "hili"]);
        expect(builder.build("ひゅ")).toEqual(["hyu", "hixyu", "hilyu"]);
        expect(builder.build("ひぇ")).toEqual(["hye", "hixe", "hile"]);
        expect(builder.build("ひょ")).toEqual(["hyo", "hixyo", "hilyo"]);
        expect(builder.build("びゃ")).toEqual(["bya", "bixya", "bilya"]);
        expect(builder.build("びぃ")).toEqual(["byi", "bixi", "bili"]);
        expect(builder.build("びゅ")).toEqual(["byu", "bixyu", "bilyu"]);
        expect(builder.build("びぇ")).toEqual(["bye", "bixe", "bile"]);
        expect(builder.build("びょ")).toEqual(["byo", "bixyo", "bilyo"]);
        expect(builder.build("ぴゃ")).toEqual(["pya", "pixya", "pilya"]);
        expect(builder.build("ぴぃ")).toEqual(["pyi", "pixi", "pili"]);
        expect(builder.build("ぴゅ")).toEqual(["pyu", "pixyu", "pilyu"]);
        expect(builder.build("ぴぇ")).toEqual(["pye", "pixe", "pile"]);
        expect(builder.build("ぴょ")).toEqual(["pyo", "pixyo", "pilyo"]);
        expect(builder.build("ふぁ")).toEqual(["fa", "fwa", "huxa", "hula", "fuxa", "fula"]);
        expect(builder.build("ふぃ")).toEqual(["fi", "fyi", "fwi", "huxi", "huli", "fuxi", "fuli"]);
        expect(builder.build("ふぇ")).toEqual(["fe", "fye","fwe", "huxe", "hule", "fuxe", "fule"]);
        expect(builder.build("ふぉ")).toEqual(["fo", "fwo", "huxo", "hulo", "fuxo", "fulo"]);
        expect(builder.build("ふゃ")).toEqual(["fya", "huxya", "hulya", "fuxya", "fulya"]);
        expect(builder.build("ふゅ")).toEqual(["fyu", "huxyu", "hulyu", "fuxyu", "fulyu"]);
        expect(builder.build("ふょ")).toEqual(["fyo", "huxyo", "hulyo", "fuxyo", "fulyo"]);
        expect(builder.build("みゃ")).toEqual(["mya", "mixya", "milya"]);
        expect(builder.build("みぃ")).toEqual(["myi", "mixi", "mili"]);
        expect(builder.build("みゅ")).toEqual(["myu", "mixyu", "milyu"]);
        expect(builder.build("みぇ")).toEqual(["mye", "mixe", "mile"]);
        expect(builder.build("みょ")).toEqual(["myo", "mixyo", "milyo"]);
        expect(builder.build("りゃ")).toEqual(["rya", "rixya", "rilya"]);
        expect(builder.build("りぃ")).toEqual(["ryi", "rixi", "rili"]);
        expect(builder.build("りゅ")).toEqual(["ryu", "rixyu", "rilyu"]);
        expect(builder.build("りぇ")).toEqual(["rye", "rixe", "rile"]);
        expect(builder.build("りょ")).toEqual(["ryo", "rixyo", "rilyo"]);
        expect(builder.build("ヴぁ")).toEqual(["va"]);
        expect(builder.build("ヴぃ")).toEqual(["vi"]);
        expect(builder.build("ヴ")).toEqual(["vu"]);
        expect(builder.build("ヴぇ")).toEqual(["ve"]);
        expect(builder.build("ヴぉ")).toEqual(["vo"]);
        expect(builder.build("ぁ")).toEqual(["xa", "la"]);
        expect(builder.build("ぃ")).toEqual(["xi", "li"]);
        expect(builder.build("ぅ")).toEqual(["xu", "lu"]);
        expect(builder.build("ぇ")).toEqual(["xe", "le"]);
        expect(builder.build("ぉ")).toEqual(["xo", "lo"]);
        expect(builder.build("ゃ")).toEqual(["xya", "lya"]);
        expect(builder.build("ゅ")).toEqual(["xyu", "lyu"]);
        expect(builder.build("ょ")).toEqual(["xyo", "lyo"]);
        expect(builder.build("っ")).toEqual(["xtu", "ltu", "xtsu", "ltsu"]);
        expect(builder.build("ゎ")).toEqual(["xwa", "lwa"]);
    })
})