"use strict";
var MoraRomanBuilder = require("../../src/mora/MoraRomanBuilder");
var builder = new MoraRomanBuilder();
describe("Roman Builder Test", () => {
    test("hiragana to roman", () => {
        expect(builder.build("あ")).toEqual(["a"]);
        expect(builder.build("い")).toEqual(["yi", "i"]);
        expect(builder.build("う")).toEqual(["wu", "whu", "u"]);
        expect(builder.build("え")).toEqual(["e"]);
        expect(builder.build("お")).toEqual(["o"]);
        expect(builder.build("か")).toEqual(["ka", "ca"]);
        expect(builder.build("き")).toEqual(["ki"]);
        expect(builder.build("く")).toEqual(["ku", "cu", "qu"]);
        expect(builder.build("け")).toEqual(["ke"]);
        expect(builder.build("こ")).toEqual(["ko", "co"]);
        expect(builder.build("さ")).toEqual(["sa"]);
        expect(builder.build("し")).toEqual(["si", "shi", "ci"]);
        expect(builder.build("す")).toEqual(["su"]);
        expect(builder.build("せ")).toEqual(["se", "ce"]);
        expect(builder.build("そ")).toEqual(["so"]);
        expect(builder.build("た")).toEqual(["ta"]);
        expect(builder.build("ち")).toEqual(["ti", "chi"]);
        expect(builder.build("つ")).toEqual(["tu", "tsu"]);
        expect(builder.build("て")).toEqual(["te"]);
        expect(builder.build("と")).toEqual(["to"]);
        expect(builder.build("な")).toEqual(["na"]);
        expect(builder.build("に")).toEqual(["ni"]);
        expect(builder.build("ぬ")).toEqual(["nu"]);
        expect(builder.build("ね")).toEqual(["ne"]);
        expect(builder.build("の")).toEqual(["no"]);
        expect(builder.build("は")).toEqual(["ha"]);
        expect(builder.build("ひ")).toEqual(["hi"]);
        expect(builder.build("ふ")).toEqual(["hu", "fu"]);
        expect(builder.build("へ")).toEqual(["he"]);
        expect(builder.build("ほ")).toEqual(["ho"]);
        expect(builder.build("ま")).toEqual(["ma"]);
        expect(builder.build("み")).toEqual(["mi"]);
        expect(builder.build("む")).toEqual(["mu"]);
        expect(builder.build("め")).toEqual(["me"]);
        expect(builder.build("も")).toEqual(["mo"]);
        expect(builder.build("や")).toEqual(["ya"]);
        expect(builder.build("ゆ")).toEqual(["yu"]);
        expect(builder.build("よ")).toEqual(["yo"]);
        expect(builder.build("ら")).toEqual(["ra"]);
        expect(builder.build("り")).toEqual(["ri"]);
        expect(builder.build("る")).toEqual(["ru"]);
        expect(builder.build("れ")).toEqual(["re"]);
        expect(builder.build("ろ")).toEqual(["ro"]);
        expect(builder.build("わ")).toEqual(["wa"]);
        expect(builder.build("を")).toEqual(["wo"]);
        expect(builder.build("ん")).toEqual(["nn", "xn"]);
        expect(builder.build("が")).toEqual(["ga"]);
        expect(builder.build("ぎ")).toEqual(["gi"]);
        expect(builder.build("ぐ")).toEqual(["gu"]);
        expect(builder.build("げ")).toEqual(["ge"]);
        expect(builder.build("ご")).toEqual(["go"]);
        expect(builder.build("ざ")).toEqual(["za"]);
        expect(builder.build("じ")).toEqual(["zi", "ji"]);
        expect(builder.build("ず")).toEqual(["zu"]);
        expect(builder.build("ぜ")).toEqual(["ze"]);
        expect(builder.build("ぞ")).toEqual(["zo"]);
        expect(builder.build("だ")).toEqual(["da"]);
        expect(builder.build("ぢ")).toEqual(["di"]);
        expect(builder.build("づ")).toEqual(["du"]);
        expect(builder.build("で")).toEqual(["de"]);
        expect(builder.build("ど")).toEqual(["do"]);
        expect(builder.build("ば")).toEqual(["ba"]);
        expect(builder.build("び")).toEqual(["bi"]);
        expect(builder.build("ぶ")).toEqual(["bu"]);
        expect(builder.build("べ")).toEqual(["be"]);
        expect(builder.build("ぼ")).toEqual(["bo"]);
        expect(builder.build("ぱ")).toEqual(["pa"]);
        expect(builder.build("ぴ")).toEqual(["pi"]);
        expect(builder.build("ぷ")).toEqual(["pu"]);
        expect(builder.build("ぺ")).toEqual(["pe"]);
        expect(builder.build("ぽ")).toEqual(["po"]);
        expect(builder.build("いぇ")).toEqual(["ye", "yixe", "yile", "ixe", "ile"]);
        expect(builder.build("うぃ")).toEqual(["wi", "wuxi", "wuli", "whuxi", "whuli", "uxi", "uli"]);
        expect(builder.build("うぇ")).toEqual(["we", "wuxe", "wule", "whuxe", "whule","uxe", "ule"]);
        expect(builder.build("きゃ")).toEqual(["kya", "kixya", "kilya"]);
        expect(builder.build("きぃ")).toEqual(["kyi", "kixi", "kili"]);
        expect(builder.build("きゅ")).toEqual(["kyu", "kixyu", "kilyu"]);
        expect(builder.build("きぇ")).toEqual(["kye", "kixe", "kile"]);
        expect(builder.build("きょ")).toEqual(["kyo", "kixyo", "kilyo"]);
        expect(builder.build("ぎゃ")).toEqual(["gya", "gixya", "gilya"]);
        expect(builder.build("ぎぃ")).toEqual(["gyi", "gixi", "gili"]);
        expect(builder.build("ぎゅ")).toEqual(["gyu", "gixyu", "gilyu"]);
        expect(builder.build("ぎぇ")).toEqual(["gye", "gixe", "gile"]);
        expect(builder.build("ぎょ")).toEqual(["gyo", "gixyo", "gilyo"]);
        expect(builder.build("くぁ")).toEqual(["qa", "kwa", "kuxa", "kula", "cuxa", "cula", "quxa", "qula"]);
        expect(builder.build("くぃ")).toEqual(["qi", "kwi", "kuxi", "kuli", "cuxi", "culi", "quxi", "quli"]);
        expect(builder.build("くぇ")).toEqual(["qe", "kwe", "kuxe", "kule", "cuxe", "cule", "quxe", "qule"]);
        expect(builder.build("くぉ")).toEqual(["qo", "kwo", "kuxo", "kulo", "cuxo", "culo", "quxo", "qulo"]);
        expect(builder.build("しゃ")).toEqual(["sha", "sya", "sixya", "silya", "shixya", "shilya", "cixya", "cilya"]);
        expect(builder.build("しぃ")).toEqual(["syi", "sixi", "sili", "shixi", "shili",  "cixi", "cili"]);
        expect(builder.build("しゅ")).toEqual(["shu", "syu", "sixyu", "silyu", "shixyu", "shilyu", "cixyu", "cilyu"]);
        expect(builder.build("しぇ")).toEqual(["she", "sye", "sixe", "sile", "shixe", "shile", "cixe", "cile"]);
        expect(builder.build("しょ")).toEqual(["sho", "syo", "sixyo", "silyo", "shixyo", "shilyo", "cixyo", "cilyo"]);
        expect(builder.build("じゃ")).toEqual(["ja", "jya", "zixya", "zilya", "jixya", "jilya"]);
        expect(builder.build("じぃ")).toEqual(["jyi", "zixi", "zili", "jixi", "jili"]);
        expect(builder.build("じゅ")).toEqual(["ju", "jyu", "zixyu", "zilyu", "jixyu", "jilyu"]);
        expect(builder.build("じぇ")).toEqual(["je", "jye", "zixe", "zile", "jixe", "jile"]);
        expect(builder.build("じょ")).toEqual(["jo", "jyo", "zixyo", "zilyo", "jixyo", "jilyo"]);
        expect(builder.build("ちゃ")).toEqual(["cha", "cya", "tya", "tixya", "tilya", "chixya", "chilya"]);
        expect(builder.build("ちぃ")).toEqual(["cyi", "tyi", "tixi", "tili", "chixi", "chili"]);
        expect(builder.build("ちゅ")).toEqual(["chu", "cyu", "tyu", "tixyu", "tilyu", "chixyu", "chilyu"]);
        expect(builder.build("ちぇ")).toEqual(["che", "cye", "tye", "tixe", "tile", "chixe", "chile"]);
        expect(builder.build("ちょ")).toEqual(["cho", "cyo", "tyo", "tixyo", "tilyo", "chixyo", "chilyo"]);
        expect(builder.build("ぢゃ")).toEqual(["dya", "dixya", "dilya"]);
        expect(builder.build("ぢぃ")).toEqual(["dyi", "dixi", "dili"]);
        expect(builder.build("ぢゅ")).toEqual(["dyu", "dixyu", "dilyu"]);
        expect(builder.build("ぢぇ")).toEqual(["dye", "dixe", "dile"]);
        expect(builder.build("ぢょ")).toEqual(["dyo", "dixyo", "dilyo"]);
        expect(builder.build("つぁ")).toEqual(["tsa", "tuxa", "tula", "tsuxa", "tsula"]);
        expect(builder.build("つぃ")).toEqual(["tsi", "tuxi", "tuli", "tsuxi", "tsuli"]);
        expect(builder.build("つぇ")).toEqual(["tse", "tuxe", "tule", "tsuxe", "tsule"]);
        expect(builder.build("つぉ")).toEqual(["tso", "tuxo", "tulo", "tsuxo", "tsulo"]);
        expect(builder.build("てゃ")).toEqual(["tha", "texya", "telya"]);
        expect(builder.build("てぃ")).toEqual(["thi", "texi", "teli"]);
        expect(builder.build("てゅ")).toEqual(["thu", "texyu", "telyu"]);
        expect(builder.build("てぇ")).toEqual(["the", "texe", "tele"]);
        expect(builder.build("てょ")).toEqual(["tho", "texyo", "telyo"]);
        expect(builder.build("でゃ")).toEqual(["dha", "dexya", "delya"]);
        expect(builder.build("でぃ")).toEqual(["dhi", "dexi", "deli"]);
        expect(builder.build("でゅ")).toEqual(["dhu", "dexyu", "delyu"]);
        expect(builder.build("でぇ")).toEqual(["dhe", "dexe", "dele"]);
        expect(builder.build("でょ")).toEqual(["dho", "dexyo", "delyo"]);
        expect(builder.build("にゃ")).toEqual(["nya", "nixya", "nilya"]);
        expect(builder.build("にぃ")).toEqual(["nyi", "nixi", "nili"]);
        expect(builder.build("にゅ")).toEqual(["nyu", "nixyu", "nilyu"]);
        expect(builder.build("にぇ")).toEqual(["nye", "nixe", "nile"]);
        expect(builder.build("にょ")).toEqual(["nyo", "nixyo", "nilyo"]);
        expect(builder.build("ひゃ")).toEqual(["hya", "hixya", "hilya"]);
        expect(builder.build("ひぃ")).toEqual(["hyi", "hixi", "hili"]);
        expect(builder.build("ひゅ")).toEqual(["hyu", "hixyu", "hilyu"]);
        expect(builder.build("ひぇ")).toEqual(["hye", "hixe", "hile"]);
        expect(builder.build("ひょ")).toEqual(["hyo", "hixyo", "hilyo"]);
        expect(builder.build("びゃ")).toEqual(["bya", "bixya", "bilya"]);
        expect(builder.build("びぃ")).toEqual(["byi", "bixi", "bili"]);
        expect(builder.build("びゅ")).toEqual(["byu", "bixyu", "bilyu"]);
        expect(builder.build("びぇ")).toEqual(["bye", "bixe", "bile"]);
        expect(builder.build("びょ")).toEqual(["byo", "bixyo", "bilyo"]);
        expect(builder.build("ぴゃ")).toEqual(["pya", "pixya", "pilya"]);
        expect(builder.build("ぴぃ")).toEqual(["pyi", "pixi", "pili"]);
        expect(builder.build("ぴゅ")).toEqual(["pyu", "pixyu", "pilyu"]);
        expect(builder.build("ぴぇ")).toEqual(["pye", "pixe", "pile"]);
        expect(builder.build("ぴょ")).toEqual(["pyo", "pixyo", "pilyo"]);
        expect(builder.build("ふぁ")).toEqual(["fa", "fwa", "huxa", "hula", "fuxa", "fula"]);
        expect(builder.build("ふぃ")).toEqual(["fi", "fyi", "fwi", "huxi", "huli", "fuxi", "fuli"]);
        expect(builder.build("ふぇ")).toEqual(["fe", "fye", "fwe", "huxe", "hule", "fuxe", "fule"]);
        expect(builder.build("ふぉ")).toEqual(["fo", "fwo", "huxo", "hulo", "fuxo", "fulo"]);
        expect(builder.build("ふゃ")).toEqual(["fya", "huxya", "hulya", "fuxya", "fulya"]);
        expect(builder.build("ふゅ")).toEqual(["fyu", "huxyu", "hulyu", "fuxyu", "fulyu"]);
        expect(builder.build("ふょ")).toEqual(["fyo", "huxyo", "hulyo", "fuxyo", "fulyo"]);
        expect(builder.build("みゃ")).toEqual(["mya", "mixya", "milya"]);
        expect(builder.build("みぃ")).toEqual(["myi", "mixi", "mili"]);
        expect(builder.build("みゅ")).toEqual(["myu", "mixyu", "milyu"]);
        expect(builder.build("みぇ")).toEqual(["mye", "mixe", "mile"]);
        expect(builder.build("みょ")).toEqual(["myo", "mixyo", "milyo"]);
        expect(builder.build("りゃ")).toEqual(["rya", "rixya", "rilya"]);
        expect(builder.build("りぃ")).toEqual(["ryi", "rixi", "rili"]);
        expect(builder.build("りゅ")).toEqual(["ryu", "rixyu", "rilyu"]);
        expect(builder.build("りぇ")).toEqual(["rye", "rixe", "rile"]);
        expect(builder.build("りょ")).toEqual(["ryo", "rixyo", "rilyo"]);
        expect(builder.build("ゔぁ")).toEqual(["va"]);
        expect(builder.build("ゔぃ")).toEqual(["vi"]);
        expect(builder.build("ゔ")).toEqual(["vu"]);
        expect(builder.build("ゔぇ")).toEqual(["ve"]);
        expect(builder.build("ゔぉ")).toEqual(["vo"]);
        expect(builder.build("ぁ")).toEqual(["xa", "la"]);
        expect(builder.build("ぃ")).toEqual(["xi", "li"]);
        expect(builder.build("ぅ")).toEqual(["xu", "lu"]);
        expect(builder.build("ぇ")).toEqual(["xe", "le"]);
        expect(builder.build("ぉ")).toEqual(["xo", "lo"]);
        expect(builder.build("ゃ")).toEqual(["xya", "lya"]);
        expect(builder.build("ゅ")).toEqual(["xyu", "lyu"]);
        expect(builder.build("ょ")).toEqual(["xyo", "lyo"]);
        expect(builder.build("っ")).toEqual(["xtu", "ltu", "xtsu", "ltsu"]);
        expect(builder.build("ゎ")).toEqual(["xwa", "lwa"]);
    })
    test("nn after", () => {
        expect(builder.build("ん", "あ")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "い")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "う")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "え")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "お")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "か")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "き")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "く")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "け")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "こ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "さ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "し")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "す")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "せ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "そ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "た")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ち")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "つ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "て")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "と")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "な")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "に")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "ぬ")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "ね")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "の")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "は")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ひ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "へ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ほ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ま")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "み")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "む")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "め")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "も")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "や")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゆ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "よ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ら")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "り")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "る")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "れ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ろ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "わ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "を")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ん")).toEqual(["nn", "xn"]);
        expect(builder.build("ん", "が")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぎ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぐ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "げ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ご")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ざ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "じ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ず")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぜ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぞ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "だ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぢ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "づ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "で")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ど")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ば")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "び")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぶ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "べ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぼ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぱ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぴ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぷ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぺ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぽ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "いぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "うぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "うぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "きゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "きぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "きゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "きぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "きょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぎゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぎぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぎゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぎぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぎょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "くぁ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "くぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "くぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "くぉ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "しゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "しぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "しゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "しぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "しょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "じゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "じぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "じゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "じぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "じょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ちゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ちぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ちゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ちぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ちょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぢぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぢゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぢぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぢょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "つぁ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "つぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "つぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "つぉ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "てゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "てぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "てゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "てぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "てょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "でゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "でぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "でゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "でぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "でょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "にゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "にぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "にゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "にぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "にょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ひゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ひぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ひゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ひぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ひょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "びゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "びぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "びゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "びぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "びょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぴゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぴぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぴゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぴぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぴょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふぁ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふぉ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ふょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "みゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "みぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "みゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "みぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "みょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "りゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "りぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "りゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "りぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "りょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゔぁ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゔぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゔ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゔぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゔぉ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぁ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぇ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ぉ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゃ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゅ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ょ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "っ")).toEqual(["nn", "xn", "n"]);
        expect(builder.build("ん", "ゎ")).toEqual(["nn", "xn", "n"]);
    });
    test("xtu after", () => {
        expect(builder.build("っ", "あ")).toEqual(["xtu", "ltu", "xtsu", "ltsu"]);
        expect(builder.build("っ", "い")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "y"]);
        expect(builder.build("っ", "う")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "w"]);
        expect(builder.build("っ", "え")).toEqual(["xtu", "ltu", "xtsu", "ltsu"]);
        expect(builder.build("っ", "お")).toEqual(["xtu", "ltu", "xtsu", "ltsu"]);
        expect(builder.build("っ", "か")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k", "c"]);
        expect(builder.build("っ", "き")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k"]);
        expect(builder.build("っ", "く")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k", "c", "q"]);
        expect(builder.build("っ", "け")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k"]);
        expect(builder.build("っ", "こ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k", "c"]);
        expect(builder.build("っ", "さ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s"]);
        expect(builder.build("っ", "し")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s", "c"]);
        expect(builder.build("っ", "す")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s"]);
        expect(builder.build("っ", "せ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s", "c"]);
        expect(builder.build("っ", "そ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s"]);
        expect(builder.build("っ", "た")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "ち")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t", "c"]);
        expect(builder.build("っ", "つ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "て")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "と")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "な")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "に")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "ぬ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "ね")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "の")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "は")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ひ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ふ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "へ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ほ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ま")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "み")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "む")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "め")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "も")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "や")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "y"]);
        expect(builder.build("っ", "ゆ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "y"]);
        expect(builder.build("っ", "よ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "y"]);
        expect(builder.build("っ", "ら")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "り")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "る")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "れ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "ろ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "わ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "w"]);
        expect(builder.build("っ", "を")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "w"]);
        expect(builder.build("っ", "ん")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x"]);
        expect(builder.build("っ", "が")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ぎ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ぐ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "げ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ご")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ざ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z"]);
        expect(builder.build("っ", "じ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z", "j"]);
        expect(builder.build("っ", "ず")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z"]);
        expect(builder.build("っ", "ぜ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z"]);
        expect(builder.build("っ", "ぞ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z"]);
        expect(builder.build("っ", "だ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "ぢ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "づ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "で")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "ど")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "ば")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "び")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "ぶ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "べ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "ぼ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "ぱ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぴ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぷ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぺ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぽ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "いぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "y"]);
        expect(builder.build("っ", "うぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "w"]);
        expect(builder.build("っ", "うぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "w"]);
        expect(builder.build("っ", "きゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k"]);
        expect(builder.build("っ", "きぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k"]);
        expect(builder.build("っ", "きゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k"]);
        expect(builder.build("っ", "きぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k"]);
        expect(builder.build("っ", "きょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k"]);
        expect(builder.build("っ", "ぎゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ぎぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ぎゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ぎぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "ぎょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "g"]);
        expect(builder.build("っ", "くぁ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k", "c", "q"]);
        expect(builder.build("っ", "くぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k", "c", "q"]);
        expect(builder.build("っ", "くぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k", "c", "q"]);
        expect(builder.build("っ", "くぉ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "k", "c", "q"]);
        expect(builder.build("っ", "しゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s", "c"]);
        expect(builder.build("っ", "しぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s", "c"]);
        expect(builder.build("っ", "しゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s", "c"]);
        expect(builder.build("っ", "しぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s", "c"]);
        expect(builder.build("っ", "しょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "s", "c"]);
        expect(builder.build("っ", "じゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z", "j"]);
        expect(builder.build("っ", "じぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z", "j"]);
        expect(builder.build("っ", "じゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z", "j"]);
        expect(builder.build("っ", "じぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z", "j"]);
        expect(builder.build("っ", "じょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "z", "j"]);
        expect(builder.build("っ", "ちゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t", "c"]);
        expect(builder.build("っ", "ちぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t", "c"]);
        expect(builder.build("っ", "ちゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t", "c"]);
        expect(builder.build("っ", "ちぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t", "c"]);
        expect(builder.build("っ", "ちょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t", "c"]);
        expect(builder.build("っ", "ぢぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "ぢゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "ぢぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "ぢょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "つぁ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "つぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "つぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "つぉ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "てゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "てぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "てゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "てぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "てょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "t"]);
        expect(builder.build("っ", "でゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "でぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "でゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "でぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "でょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "d"]);
        expect(builder.build("っ", "にゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "にぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "にゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "にぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "にょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "n"]);
        expect(builder.build("っ", "ひゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ひぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ひゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ひぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "ひょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h"]);
        expect(builder.build("っ", "びゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "びぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "びゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "びぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "びょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "b"]);
        expect(builder.build("っ", "ぴゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぴぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぴゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぴぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ぴょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "p"]);
        expect(builder.build("っ", "ふぁ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "ふぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "ふぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "ふぉ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "ふゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "ふゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "ふょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "h", "f"]);
        expect(builder.build("っ", "みゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "みぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "みゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "みぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "みょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "m"]);
        expect(builder.build("っ", "りゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "りぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "りゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "りぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "りょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "r"]);
        expect(builder.build("っ", "ゔぁ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "v"]);
        expect(builder.build("っ", "ゔぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "v"]);
        expect(builder.build("っ", "ゔ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "v"]);
        expect(builder.build("っ", "ゔぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "v"]);
        expect(builder.build("っ", "ゔぉ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "v"]);
        expect(builder.build("っ", "ぁ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ぃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ぅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ぇ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ぉ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ゃ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ゅ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ょ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "っ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
        expect(builder.build("っ", "ゎ")).toEqual(["xtu", "ltu", "xtsu", "ltsu", "x", "l"]);
    });

    test("number", () => {
        expect(builder.build("１")).toEqual(["1"]);
        expect(builder.build("２")).toEqual(["2"]);
        expect(builder.build("３")).toEqual(["3"]);
        expect(builder.build("４")).toEqual(["4"]);
        expect(builder.build("５")).toEqual(["5"]);
        expect(builder.build("６")).toEqual(["6"]);
        expect(builder.build("７")).toEqual(["7"]);
        expect(builder.build("８")).toEqual(["8"]);
        expect(builder.build("９")).toEqual(["9"]);
        expect(builder.build("１０")).toEqual(["10"]);
        expect(builder.build("１００")).toEqual(["100"]);
        expect(builder.build("１０００")).toEqual(["1000"]);
        expect(builder.build("１００００")).toEqual(["10000"]);
        expect(builder.build("1")).toEqual(["1"]);
        expect(builder.build("2")).toEqual(["2"]);
        expect(builder.build("3")).toEqual(["3"]);
        expect(builder.build("4")).toEqual(["4"]);
        expect(builder.build("5")).toEqual(["5"]);
        expect(builder.build("6")).toEqual(["6"]);
        expect(builder.build("7")).toEqual(["7"]);
        expect(builder.build("8")).toEqual(["8"]);
        expect(builder.build("9")).toEqual(["9"]);
        expect(builder.build("10")).toEqual(["10"]);
        expect(builder.build("100")).toEqual(["100"]);
        expect(builder.build("1000")).toEqual(["1000"]);
        expect(builder.build("10000")).toEqual(["10000"]);
    });

    test("symbol", () => {
        expect(builder.build("！")).toEqual(["!"]);
        expect(builder.build("＂")).toEqual(["\""]);
        expect(builder.build("＃")).toEqual(["#"]);
        expect(builder.build("＄")).toEqual(["$"]);
        expect(builder.build("％")).toEqual(["%"]);
        expect(builder.build("＆")).toEqual(["&"]);
        expect(builder.build("＇")).toEqual(["'"]);
        expect(builder.build("（")).toEqual(["("]);
        expect(builder.build("）")).toEqual([")"]);
        expect(builder.build("＊")).toEqual(["*"]);
        expect(builder.build("＋")).toEqual(["+"]);
        expect(builder.build("，")).toEqual([","]);
        expect(builder.build("－")).toEqual(["-"]);
        expect(builder.build("ー")).toEqual(["-"]);
        expect(builder.build("．")).toEqual(["."]);
        expect(builder.build("／")).toEqual(["/"]);
        expect(builder.build("：")).toEqual([":"]);
        expect(builder.build("；")).toEqual([";"]);
        expect(builder.build("＜")).toEqual(["<"]);
        expect(builder.build("＝")).toEqual(["="]);
        expect(builder.build("＞")).toEqual([">"]);
        expect(builder.build("？")).toEqual(["?"]);
        expect(builder.build("＠")).toEqual(["@"]);
        expect(builder.build("［")).toEqual(["["]);
        expect(builder.build("＼")).toEqual(["\\"]);
        expect(builder.build("］")).toEqual(["]"]);
        expect(builder.build("＾")).toEqual(["^"]);
        expect(builder.build("＿")).toEqual(["_"]);
        expect(builder.build("｀")).toEqual(["`"]);
        expect(builder.build("｛")).toEqual(["{"]);
        expect(builder.build("｜")).toEqual(["|"]);
        expect(builder.build("｝")).toEqual(["}"]);
        expect(builder.build("～")).toEqual(["~"]);
        expect(builder.build("、")).toEqual([","]);
        expect(builder.build("。")).toEqual(["."]);
        expect(builder.build("「")).toEqual(["\""]);
        expect(builder.build("」")).toEqual(["\""]);
        expect(builder.build("　")).toEqual([" "]);
        expect(builder.build("!")).toEqual(["!"]);
        expect(builder.build("\"")).toEqual(["\""]);
        expect(builder.build("#")).toEqual(["#"]);
        expect(builder.build("$")).toEqual(["$"]);
        expect(builder.build("%")).toEqual(["%"]);
        expect(builder.build("&")).toEqual(["&"]);
        expect(builder.build("'")).toEqual(["'"]);
        expect(builder.build("(")).toEqual(["("]);
        expect(builder.build(")")).toEqual([")"]);
        expect(builder.build("*")).toEqual(["*"]);
        expect(builder.build("+")).toEqual(["+"]);
        expect(builder.build(",")).toEqual([","]);
        expect(builder.build("-")).toEqual(["-"]);
        expect(builder.build(".")).toEqual(["."]);
        expect(builder.build("/")).toEqual(["/"]);
        expect(builder.build(":")).toEqual([":"]);
        expect(builder.build(";")).toEqual([";"]);
        expect(builder.build("<")).toEqual(["<"]);
        expect(builder.build("=")).toEqual(["="]);
        expect(builder.build(">")).toEqual([">"]);
        expect(builder.build("?")).toEqual(["?"]);
        expect(builder.build("@")).toEqual(["@"]);
        expect(builder.build("[")).toEqual(["["]);
        expect(builder.build("\\")).toEqual(["\\"]);
        expect(builder.build("]")).toEqual(["]"]);
        expect(builder.build("^")).toEqual(["^"]);
        expect(builder.build("_")).toEqual(["_"]);
        expect(builder.build("`")).toEqual(["`"]);
        expect(builder.build("{")).toEqual(["{"]);
        expect(builder.build("|")).toEqual(["|"]);
        expect(builder.build("}")).toEqual(["}"]);
        expect(builder.build("~")).toEqual(["~"]);
        expect(builder.build(" ")).toEqual([" "]);
    });

    test("roman", () => {
        expect(builder.build("ａ")).toEqual(["a"]);
        expect(builder.build("ｂ")).toEqual(["b"]);
        expect(builder.build("ｃ")).toEqual(["c"]);
        expect(builder.build("ｄ")).toEqual(["d"]);
        expect(builder.build("ｅ")).toEqual(["e"]);
        expect(builder.build("ｆ")).toEqual(["f"]);
        expect(builder.build("ｇ")).toEqual(["g"]);
        expect(builder.build("ｈ")).toEqual(["h"]);
        expect(builder.build("ｉ")).toEqual(["i"]);
        expect(builder.build("ｊ")).toEqual(["j"]);
        expect(builder.build("ｋ")).toEqual(["k"]);
        expect(builder.build("ｌ")).toEqual(["l"]);
        expect(builder.build("ｍ")).toEqual(["m"]);
        expect(builder.build("ｎ")).toEqual(["n"]);
        expect(builder.build("ｏ")).toEqual(["o"]);
        expect(builder.build("ｐ")).toEqual(["p"]);
        expect(builder.build("ｑ")).toEqual(["q"]);
        expect(builder.build("ｒ")).toEqual(["r"]);
        expect(builder.build("ｓ")).toEqual(["s"]);
        expect(builder.build("ｔ")).toEqual(["t"]);
        expect(builder.build("ｕ")).toEqual(["u"]);
        expect(builder.build("ｖ")).toEqual(["v"]);
        expect(builder.build("ｗ")).toEqual(["w"]);
        expect(builder.build("ｘ")).toEqual(["x"]);
        expect(builder.build("ｙ")).toEqual(["y"]);
        expect(builder.build("ｚ")).toEqual(["z"]);
        expect(builder.build("Ａ")).toEqual(["A"]);
        expect(builder.build("Ｂ")).toEqual(["B"]);
        expect(builder.build("Ｃ")).toEqual(["C"]);
        expect(builder.build("Ｄ")).toEqual(["D"]);
        expect(builder.build("Ｅ")).toEqual(["E"]);
        expect(builder.build("Ｆ")).toEqual(["F"]);
        expect(builder.build("Ｇ")).toEqual(["G"]);
        expect(builder.build("Ｈ")).toEqual(["H"]);
        expect(builder.build("Ｉ")).toEqual(["I"]);
        expect(builder.build("Ｊ")).toEqual(["J"]);
        expect(builder.build("Ｋ")).toEqual(["K"]);
        expect(builder.build("Ｌ")).toEqual(["L"]);
        expect(builder.build("Ｍ")).toEqual(["M"]);
        expect(builder.build("Ｎ")).toEqual(["N"]);
        expect(builder.build("Ｏ")).toEqual(["O"]);
        expect(builder.build("Ｐ")).toEqual(["P"]);
        expect(builder.build("Ｑ")).toEqual(["Q"]);
        expect(builder.build("Ｒ")).toEqual(["R"]);
        expect(builder.build("Ｓ")).toEqual(["S"]);
        expect(builder.build("Ｔ")).toEqual(["T"]);
        expect(builder.build("Ｕ")).toEqual(["U"]);
        expect(builder.build("Ｖ")).toEqual(["V"]);
        expect(builder.build("Ｗ")).toEqual(["W"]);
        expect(builder.build("Ｘ")).toEqual(["X"]);
        expect(builder.build("Ｙ")).toEqual(["Y"]);
        expect(builder.build("Ｚ")).toEqual(["Z"]);
        expect(builder.build("a")).toEqual(["a"]);
        expect(builder.build("b")).toEqual(["b"]);
        expect(builder.build("c")).toEqual(["c"]);
        expect(builder.build("d")).toEqual(["d"]);
        expect(builder.build("e")).toEqual(["e"]);
        expect(builder.build("f")).toEqual(["f"]);
        expect(builder.build("g")).toEqual(["g"]);
        expect(builder.build("h")).toEqual(["h"]);
        expect(builder.build("i")).toEqual(["i"]);
        expect(builder.build("j")).toEqual(["j"]);
        expect(builder.build("k")).toEqual(["k"]);
        expect(builder.build("l")).toEqual(["l"]);
        expect(builder.build("m")).toEqual(["m"]);
        expect(builder.build("n")).toEqual(["n"]);
        expect(builder.build("o")).toEqual(["o"]);
        expect(builder.build("p")).toEqual(["p"]);
        expect(builder.build("q")).toEqual(["q"]);
        expect(builder.build("r")).toEqual(["r"]);
        expect(builder.build("s")).toEqual(["s"]);
        expect(builder.build("t")).toEqual(["t"]);
        expect(builder.build("u")).toEqual(["u"]);
        expect(builder.build("v")).toEqual(["v"]);
        expect(builder.build("w")).toEqual(["w"]);
        expect(builder.build("x")).toEqual(["x"]);
        expect(builder.build("y")).toEqual(["y"]);
        expect(builder.build("z")).toEqual(["z"]);
        expect(builder.build("A")).toEqual(["A"]);
        expect(builder.build("B")).toEqual(["B"]);
        expect(builder.build("C")).toEqual(["C"]);
        expect(builder.build("D")).toEqual(["D"]);
        expect(builder.build("E")).toEqual(["E"]);
        expect(builder.build("F")).toEqual(["F"]);
        expect(builder.build("G")).toEqual(["G"]);
        expect(builder.build("H")).toEqual(["H"]);
        expect(builder.build("I")).toEqual(["I"]);
        expect(builder.build("J")).toEqual(["J"]);
        expect(builder.build("K")).toEqual(["K"]);
        expect(builder.build("L")).toEqual(["L"]);
        expect(builder.build("M")).toEqual(["M"]);
        expect(builder.build("N")).toEqual(["N"]);
        expect(builder.build("O")).toEqual(["O"]);
        expect(builder.build("P")).toEqual(["P"]);
        expect(builder.build("Q")).toEqual(["Q"]);
        expect(builder.build("R")).toEqual(["R"]);
        expect(builder.build("S")).toEqual(["S"]);
        expect(builder.build("T")).toEqual(["T"]);
        expect(builder.build("U")).toEqual(["U"]);
        expect(builder.build("V")).toEqual(["V"]);
        expect(builder.build("W")).toEqual(["W"]);
        expect(builder.build("X")).toEqual(["X"]);
        expect(builder.build("Y")).toEqual(["Y"]);
        expect(builder.build("Z")).toEqual(["Z"]);
    });
})